AllCops:
  DisplayCopNames: true

  Include:
    - '**/Rakefile'

  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'bin/**/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false
