require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RentalsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Rental. As you add validations to Rental, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      name: "My rental",
      daily_rate: 30
    }
  end

  let(:invalid_attributes) do
    {
      invalid: "value",
      daily_rate: nil
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RentalsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all rentals as @rentals" do
      rental = Rental.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:rentals)).to eq([rental])
    end
  end

  describe "GET #show" do
    it "assigns the requested rental as @rental" do
      rental = Rental.create! valid_attributes
      get :show, params: { id: rental.to_param }, session: valid_session
      expect(assigns(:rental)).to eq(rental)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Rental" do
        expect do
          post :create, params: { rental: valid_attributes }, session: valid_session
        end.to change(Rental, :count).by(1)
      end

      it "assigns a newly created rental as @rental" do
        post :create, params: { rental: valid_attributes }, session: valid_session
        expect(assigns(:rental)).to be_a(Rental)
        expect(assigns(:rental)).to be_persisted
      end

      it "responds with status created" do
        post :create, params: { rental: valid_attributes }, session: valid_session
        expect(response).to have_http_status(:created)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved rental as @rental" do
        post :create, params: { rental: invalid_attributes }, session: valid_session
        expect(assigns(:rental)).to be_a_new(Rental)
      end

      it "responds with status unprocessable_entity" do
        post :create, params: { rental: invalid_attributes }, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) do
        {
          name: "Updated name",
          daily_rate: 40
        }
      end

      it "updates the requested rental" do
        rental = Rental.create! valid_attributes
        put :update, params: { id: rental.to_param, rental: new_attributes }, session: valid_session
        rental.reload
        expected = new_attributes

        expect(rental.name).to eq(expected[:name])
        expect(rental.daily_rate).to eq(expected[:daily_rate])
      end

      it "assigns the requested rental as @rental" do
        rental = Rental.create! valid_attributes
        put :update, params: { id: rental.to_param, rental: new_attributes }, session: valid_session
        expect(assigns(:rental)).to eq(rental)
      end

      it "responds with status ok" do
        rental = Rental.create! valid_attributes
        put :update, params: { id: rental.to_param, rental: new_attributes }, session: valid_session
        expect(response).to have_http_status(:ok)
      end
    end

    context "with invalid params" do
      it "assigns the rental as @rental" do
        rental = Rental.create! valid_attributes
        put :update, params: { id: rental.to_param, rental: invalid_attributes }, session: valid_session
        expect(assigns(:rental)).to eq(rental)
      end

      it "responds with status unprocessable_entity" do
        rental = Rental.create! valid_attributes
        put :update, params: { id: rental.to_param, rental: invalid_attributes }, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested rental" do
      rental = Rental.create! valid_attributes
      expect do
        delete :destroy, params: { id: rental.to_param }, session: valid_session
      end.to change(Rental, :count).by(-1)
    end

    it "responds with status no content" do
      rental = Rental.create! valid_attributes
      delete :destroy, params: { id: rental.to_param }, session: valid_session
      expect(response).to have_http_status(:no_content)
    end
  end
end
